### ISSUE TITLE
Adding incorrect policy, due to this lambda not able to update IP set.

### ISSUE THREAD

**Issue by vijayvikama** [aws-samples/amazon-guardduty-waf-acl#10]
it seems resource block should have [] and under that both the resource sould be mentioned

{
            "Action": [
                "wafv2:GetIPSet",
                "wafv2:UpdateIPSet"
            ],
            "Resource": "arn:aws:wafv2:us-east-1:xxxxxxxxxxxxx:global/ipset/CloudFrontBlocklistIPSetV4-xxxxxx/xxxxxxxxxxxx, arn:aws:wafv2:us-east-1:xxxxxxx:regional/ipset/RegionalBlocklistIPSetV4-xxxxxx/xxxxxxxxxxxxxxx",
            "Effect": "Allow"
 }

**Comment by cgulliver** [comment]
Fixed in CloudFomation template - commit 86d67f5
