### ISSUE TITLE
Only Blocking First Offending IP

### ISSUE THREAD

**Issue by fotzlapen** [aws-samples/amazon-guardduty-waf-acl#5]
Hi Guys,

I believe there is a bug in the script. When it receives the IP's for a scan they come in as an array. But the script only seems to be blocking the first IP in the array.

This is the offending line:

HostIp = event["detail"]["service"]["action"]["portProbeAction"]["portProbeDetails"][0]["remoteIpDetails"]["ipAddressV4"]

portProbeDetails is actually an array of remoteIpDetails that contains more than just one entry. You probably need to loop through this array to block all of the offending IPs. Otherwise you are going to miss a whole bunch of IPs that are attacking you.

I'll attach a patch that I've made but you will probably find a more elegant way to do it with better error handling than my code.

Cheers!

[Amazon_GuardDuty_NACL.patch.txt](https://github.com/aws-samples/amazon-guardduty-waf-acl/files/3357170/Amazon_GuardDuty_NACL.patch.txt)

**Comment by cgulliver** [comment]
Hi  fotzlapen - An [updated version of the Lambda code](https://github.com/aws-samples/amazon-guardduty-waf-acl/blob/dev/lambda/guardduty_to_acl_lambda.py) has been added to the dev branch. We are testing but would welcome any feedback if your also able to test. Once validated, we will update master,

**Comment by fotzlapen** [comment]
Hi Aws-Samples/Amazon-Guardduty-Waf-Acl,

Looks good to me.  It blocked all the IPs that were in my test event this
time.

Thanks very much for making this change.

Cheers,

Damon

**Comment by cgulliver** [comment]
Thanks for the feedback. This has been merged.
