### ISSUE TITLE
Update for WAFV2?

### ISSUE THREAD

**Issue by p-doyle** [aws-samples/amazon-guardduty-waf-acl#7]
Would it be possible to update this to work with the new WAF console?  I have an existing ACL created with the new console that I would like to use the IP set with.

Thanks for your work on this!

**Comment by cgulliver** [comment]
Updates for WAFv2 are in the WAFv2 branch - https://github.com/aws-samples/amazon-guardduty-waf-acl/tree/wafv2
    You will need to have the artifacts (zip files in artifacts folder) staged on S3 and also update ArtifactsBucket and ArtifactsPrefix
    Template no longer supports an existing IP sets. Regional and CloudFront IP sets are created automatically and can be included in your existing WAF rules and ACLs.
    New Regional and Global WAF ACLs can be created by changing parameter in the template from False to True
